-- Constraint: MEMBERS_TEAMID_fkey

-- ALTER TABLE public."MEMBERS" DROP CONSTRAINT "MEMBERS_TEAMID_fkey";

ALTER TABLE public."MEMBERS"
    ADD CONSTRAINT "MEMBERS_TEAMID_fkey" FOREIGN KEY ("TEAMID")
    REFERENCES public."TEAMS" ("ID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
